version: '2'

services:

  kafka:
    image: spotify/kafka
    ports:
      - "9092:9092"

  gradle:
    build: docker/gradle
    volumes:
      - ${PROJECT_DIR}:${PROJECT_DIR}
      - maven-repo:/var/lib/maven
      - gradle-dir:/var/lib/gradle
    command: sleep 1

  kafkacat:
    build: docker/kafkacat
    links:
      - kafka
    command: sleep 1

  shell:
    build: docker/shell
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${PROJECT_DIR}:${PROJECT_DIR}
    environment:
      PROJECT_DIR: ${PROJECT_DIR}
    command: sleep 1

volumes:

  maven-repo:

  gradle-dir:
