version: "2"

services:

  zookeeper:
    image: zookeeper
    ports:
      - 2181:2181
    restart: unless-stopped
    volumes:
      - zookeeper-data:/data
      - zookeeper-datalog:/datalog
    logging:
      driver: json-file
      options:
        max-size: "512k"
        max-file: "2"

  kafka:
    build: docker/kafka
    ports:
      - 9092:9092
    restart: unless-stopped
    environment:
      - KAFKA_ADVERTISED_HOST_NAME=kafka
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper
      - KAFKA_ZOOKEEPER_CONNECTION_TIMEOUT_MS=60000
      - KAFKA_DELETE_TOPIC_ENABLE=true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - kafka-data:/var/lib/kafka
    links:
      - zookeeper
    logging:
      driver: json-file
      options:
        max-size: "512k"
        max-file: "2"


  gradle:
    build: docker/gradle
    volumes:
      - ${PROJECT_DIR}:${PROJECT_DIR}
      - maven-repo:/var/lib/maven
      - gradle-dir:/var/lib/gradle
    command: sleep 1

  kafkacat:
    build: docker/kafkacat
    links:
      - kafka
    command: sleep 1

  shell:
    build: docker/shell
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${PROJECT_DIR}:${PROJECT_DIR}
    environment:
      PROJECT_DIR: ${PROJECT_DIR}
    command: sleep 1

volumes:

  zookeeper-data: {}
  zookeeper-datalog: {}

  kafka-data: {}

  maven-repo: {}

  gradle-dir: {}
